# Numeric Python

## Scientific stack

- Most python scientists, use the following libraries:
    - numpy: performant array library  (vectors and matrices)
    - matplotlib: plotting library
    - scipy: all kinds of mathematical routines
- In the rest of the course, we'll make some use of `numpy` and `matplotlib`
- They are included in all python *distributions* like Anaconda Python

## Importing the libraries

It is standard to import the libraries as `np`, and `plt`. We'll follow this convention here.

In [5]:
# these lines need to be run only once per program
import numpy as np
import matplotlib as plt

In [6]:
print(f"Numpy version {np.__version__}")
print(f"Matplotlib version{plt.__version__}")

Numpy version 1.19.4
Matplotlib version3.3.2


## Numpy

### Vector Creation

In [8]:
# an array can be created from a list of numbers
np.array([1.0, 2.0, 3.0])

array([1., 2., 3.])

In [15]:
# or initialized by specifying the length of the array
np.zeros(5)

array([0., 0., 0., 0., 0.])

### Matrix Creation

In [9]:
# an array can be created from a list of (equal size) lists
np.array([[1.0, 2.0, 3.0], [4,5,6]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
# initialize an empty matrix with the dimensions as a tuple
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### Linear Algebra

*Vector multiplications* and *Matrix multiplications* can be performed using special sign `@`

In [12]:
A = np.array([[1.0, 2.0], [2,4]])
A

array([[1., 2.],
       [2., 4.]])

In [14]:
B = np.array([1.0, 2.0])
B

array([1., 2.])

In [15]:
A@B

array([ 5., 10.])

In [16]:
A@A

array([[ 5., 10.],
       [10., 20.]])